env: {}

name: Publish

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  NPM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 100
          fetch-tags: true
      - uses: actions/setup-node@v6
        with:
          node-version: '>=22.14.0'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - run: npm ci
      - run: npm test
      - run: npm publish

      - name: Get latest tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{env.LATEST_TAG}}" --generate-notes --fail-on-no-commits
        continue-on-error: true
